"""initial_schema

Revision ID: 6ae8a10ffdf7
Revises: None
Create Date: 2026-06-13 05:18:47.184078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ae8a10ffdf7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('teacher', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('created', 'uploading', 'processing', 'completed', 'failed', name='batchstatus'), nullable=False),
    sa.Column('total_sheets', sa.Integer(), nullable=False),
    sa.Column('processed_sheets', sa.Integer(), nullable=False),
    sa.Column('flagged_count', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('max_score_per_sheet', sa.Float(), nullable=False),
    sa.Column('enable_student_portal', sa.Boolean(), nullable=False),
    sa.Column('student_access_code', sa.String(length=50), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batches_status', 'batches', ['status'], unique=False)
    op.create_index('ix_batches_user_id', 'batches', ['user_id'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('question_paper_path', sa.String(length=500), nullable=True),
    sa.Column('marking_scheme_path', sa.String(length=500), nullable=True),
    sa.Column('guidelines', sa.Text(), nullable=True),
    sa.Column('parsed_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsing_status', sa.Enum('pending', 'completed', 'failed', name='rubricparsingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('sheets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('original_file_path', sa.String(length=500), nullable=True),
    sa.Column('page_image_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotated_image_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotated_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('total_awarded_marks', sa.Float(), nullable=True),
    sa.Column('total_max_marks', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'converting', 'extracting', 'evaluating', 'annotating', 'completed', 'flagged', 'failed', name='sheetstatus'), nullable=False),
    sa.Column('ai_extraction_confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sheets_batch_id', 'sheets', ['batch_id'], unique=False)
    op.create_index('ix_sheets_roll_number', 'sheets', ['roll_number'], unique=False)
    op.create_index('ix_sheets_status', 'sheets', ['status'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sheet_id', sa.String(length=36), nullable=False),
    sa.Column('q_no', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('student_answer_transcribed', sa.Text(), nullable=True),
    sa.Column('awarded_marks', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('verdict', sa.Enum('correct', 'partial', 'wrong', 'skipped', 'diagram_correct', 'diagram_partial', 'diagram_wrong', name='evaluationverdict'), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('bbox_x', sa.Float(), nullable=True),
    sa.Column('bbox_y', sa.Float(), nullable=True),
    sa.Column('bbox_w', sa.Float(), nullable=True),
    sa.Column('bbox_h', sa.Float(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluations_is_flagged', 'evaluations', ['is_flagged'], unique=False)
    op.create_index('ix_evaluations_is_reviewed', 'evaluations', ['is_reviewed'], unique=False)
    op.create_index('ix_evaluations_sheet_id', 'evaluations', ['sheet_id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('original_ai_score', sa.Float(), nullable=False),
    sa.Column('override_score', sa.Float(), nullable=True),
    sa.Column('action', sa.Enum('pending', 'approved', 'overridden', 'recheck', name='reviewaction'), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_items_action', 'review_items', ['action'], unique=False)
    op.create_index('ix_review_items_batch_id', 'review_items', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_items_batch_id', table_name='review_items')
    op.drop_index('ix_review_items_action', table_name='review_items')
    op.drop_table('review_items')
    op.drop_index('ix_evaluations_sheet_id', table_name='evaluations')
    op.drop_index('ix_evaluations_is_reviewed', table_name='evaluations')
    op.drop_index('ix_evaluations_is_flagged', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('ix_sheets_status', table_name='sheets')
    op.drop_index('ix_sheets_roll_number', table_name='sheets')
    op.drop_index('ix_sheets_batch_id', table_name='sheets')
    op.drop_table('sheets')
    op.drop_table('rubrics')
    op.drop_index('ix_batches_user_id', table_name='batches')
    op.drop_index('ix_batches_status', table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
